# .readthedocs.yaml
version: 2

# 安装项目依赖（如 Sphinx、主题、插件）
install:
  - method: pip
    path: .
    requirements: requirements.txt  # 若有依赖文件，替换为你的文件名
  - pip install sphinx==8.2.3 myst-parser sphinx-rtd-theme  # 直接安装依赖（可选）

# 指定文档构建命令和输出目录
sphinx:
  configuration: source/conf.py  # 若 conf.py 在 source 目录下，需指定路径
  builder: html  # 生成 HTML 文档
  fail_on_warning: true  # 遇到警告时终止构建（可选）

python:
  version: 3.12
  install:
    - method: pip
      packages:
        - sphinx==8.2.3
        - myst-parser>=1.2.0
        - sphinx-rtd-theme>=1.3.0
        - sphinx-markdown-tables>=0.0.15